package com.gptimage.playground.ui.theme

import androidx.compose.ui.graphics.Color

// Brand palette
val BrandPrimary = Color(0xFF4A90E2)
val BrandPrimaryDark = Color(0xFF2E6FBF)
val BrandSecondary = Color(0xFF24C8DB)
val BrandAccent = Color(0xFFFF8A4C)

// Light scheme
val LightPrimary = Color(0xFF2E6FBF)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD6E3FF)
val LightOnPrimaryContainer = Color(0xFF001B3F)
val LightSecondary = Color(0xFF00696D)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFF6FF6FB)
val LightOnSecondaryContainer = Color(0xFF002021)
val LightTertiary = Color(0xFF825500)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDDB7)
val LightOnTertiaryContainer = Color(0xFF291800)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF7F8FA)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFE0E2EC)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightOutlineVariant = Color(0xFFC3C7CF)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF1F3F8)
val LightSurfaceContainer = Color(0xFFEBEDF2)
val LightSurfaceContainerHigh = Color(0xFFE5E8ED)
val LightSurfaceContainerHighest = Color(0xFFE0E2E7)

// Dark scheme
val DarkPrimary = Color(0xFFA8C7FF)
val DarkOnPrimary = Color(0xFF002F66)
val DarkPrimaryContainer = Color(0xFF0F4A8A)
val DarkOnPrimaryContainer = Color(0xFFD6E3FF)
val DarkSecondary = Color(0xFF4CD9DE)
val DarkOnSecondary = Color(0xFF00373A)
val DarkSecondaryContainer = Color(0xFF004F53)
val DarkOnSecondaryContainer = Color(0xFF6FF6FB)
val DarkTertiary = Color(0xFFFFB95C)
val DarkOnTertiary = Color(0xFF452B00)
val DarkTertiaryContainer = Color(0xFF633F00)
val DarkOnTertiaryContainer = Color(0xFFFFDDB7)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0A0B0D)
val DarkOnBackground = Color(0xFFE3E3E5)
val DarkSurface = Color(0xFF121417)
val DarkOnSurface = Color(0xFFE3E3E5)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C7CF)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkSurfaceContainerLowest = Color(0xFF070809)
val DarkSurfaceContainerLow = Color(0xFF0F1113)
val DarkSurfaceContainer = Color(0xFF13151A)
val DarkSurfaceContainerHigh = Color(0xFF1B1E22)
val DarkSurfaceContainerHighest = Color(0xFF26292E)
